DROP TABLE BANKBOOK;

CREATE TABLE BANKBOOK(
    USER_NO NUMBER PRIMARY KEY, --사용자번호
    BANKBOOK_NO NUMBER NOT NULL UNIQUE, -- 계좌번호
    USER_ID VARCHAR2(30) NOT NULL UNIQUE, -- 아이디
    USER_PWD VARCHAR2(30) NOT NULL, --비밀번호
    USER_NAME VARCHAR2(30) NOT NULL UNIQUE, --이름
    BALANCE NUMBER -- 잔고
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO BANKBOOK VALUES(SEQ_USERNO.NEXTVAL, 1, 'USER1', 'USER1', '백수', 0);


COMMIT;
