-----------------BASIC---------------------------------

--1
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열"
FROM TB_DEPARTMENT;

--2
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY ||'명 입니다.'
FROM TB_DEPARTMENT;

--3
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN,8 , 1) = '2'
AND ABSENCE_YN = 'Y';

--4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119');

--5
SELECT DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY;

--10
SELECT STUDENT_NO,STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,2) = 'A2'
AND STUDENT_ADDRESS LIKE '%전주%';

--------------------FUNCTION-------------------------------------
--1
SELECT STUDENT_NO AS"학번", STUDENT_NAME AS"이름", ENTRANCE_DATE AS"입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3
SELECT PROFESSOR_NAME AS"교수이름", 100-(SUBSTR(PROFESSOR_SSN,1,2)) + 24 AS"나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8, 1) = 1
ORDER BY 나이;

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2)AS"이름"
FROM TB_PROFESSOR;

--5


--6

--7

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

--9
SELECT ROUND(AVG(POINT),1)AS"평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE STUDENT_NO = 'A517178'
GROUP BY STUDENT_NAME;

--10
SELECT DEPARTMENT_NO AS"학과번호", COUNT(*) AS "학생수(명)"
FROM TB_CLASS
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ;

--11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO,1,4) AS "년도", SUM(POINT) AS "년도 별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE STUDENT_NAME = '김고운'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4);

--13
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(ABSENCE_YN) AS "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


--14

--15

----------------------------------------------------------------------------